export interface Artist {
    name: string
    image: string
}

export const artistOrder: Record<string, Artist[]> = {
    "1": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/gaia.jpg" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/gabbani.jpg" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/rkomi.jpg" },
        { "name": "Noemi - Se t'innamori muori", "image": "/noemi.jpg" },
        { "name": "Irama - Lentamente", "image": "/irama.jpg" },
        { "name": "Coma_Cose - Cuoricini", "image": "/coma-cose.jpg" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/cristicchi.jpg" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/marcella_bella.jpg" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/achille-lauro.jpg" },
        { "name": "Giorgia - La cura per me", "image": "/giorgia.jpg" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/peyote.jpg" },
        { "name": "Rose Villain - Fuorilegge", "image": "/rose_villain.jpeg" },
        { "name": "Olly - Balorda nostalgia", "image": "/olly.jpg" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/elodie.jpg" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/Shablo.jpg" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/Massimo_ranieri.jpg" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/tony_effe.jpg" },
        { "name": "Serena Brancale - Anema e core", "image": "/Serena_Brancale.jpg" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/brunori-sas.jpg" },
        { "name": "Modà - Non ti dimentico", "image": "/moda.jpg" },
        { "name": "Clara - Febbre", "image": "/clara.jpg" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi.jpg" },
        { "name": "Fedez - Battito", "image": "/fedez.jpg" },
        { "name": "Bresh - La tana del granchio", "image": "/bresh.jpg" },
        { "name": "Sarah Toscano - Amarcord", "image": "/sarah.jpg" },
        { "name": "Joan Thiele - Eco", "image": "/joan-thiele.jpg" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/rocco_hunt.jpg" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/michielin.jpg" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/the_kolors.jpg" }
    ],
    "2": [
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/rocco_hunt.jpg" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/elodie.jpg" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi.jpg" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/the_kolors.jpg" },
        { "name": "Serena Brancale - Anema e core", "image": "/Serena_Brancale.jpg" },
        { "name": "Fedez - Battito", "image": "/fedez.jpg" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/michielin.jpg" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/cristicchi.jpg" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/marcella_bella.jpg" },
        { "name": "Bresh - La tana del granchio", "image": "/bresh.jpg" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/achille-lauro.jpg" },
        { "name": "Giorgia - La cura per me", "image": "/giorgia.jpg" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/rkomi.jpg" },
        { "name": "Rose Villain - Fuorilegge", "image": "/rose_villain.jpeg" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/peyote.jpg" }
    ],
    "3": [
        { "name": "Clara - Febbre", "image": "/clara.jpg" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/brunori-sas.jpg" },
        { "name": "Sarah Toscano - Amarcord", "image": "/sarah.jpg" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/Massimo_ranieri.jpg" },
        { "name": "Joan Thiele - Eco", "image": "/joan-thiele.jpg" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/Shablo.jpg" },
        { "name": "Noemi - Se t'innamori muori", "image": "/noemi.jpg" },
        { "name": "Olly - Balorda nostalgia", "image": "/olly.jpg" },
        { "name": "Coma_Cose - Cuoricini", "image": "/coma-cose.jpg" },
        { "name": "Modà - Non ti dimentico", "image": "/moda.jpg" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/tony_effe.jpg" },
        { "name": "Irama - Lentamente", "image": "/irama.jpg" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/gabbani.jpg" },
        { "name": "Gaia - Chiamo io chiami tu", "image": "/gaia.jpg" },
    ],
    "4": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/gaia.jpg" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/gabbani.jpg" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/rkomi.jpg" },
        { "name": "Noemi - Se t'innamori muori", "image": "/noemi.jpg" },
        { "name": "Irama - Lentamente", "image": "/irama.jpg" },
        { "name": "Coma_Cose - Cuoricini", "image": "/coma-cose.jpg" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/cristicchi.jpg" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/marcella_bella.jpg" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/achille-lauro.jpg" },
        { "name": "Giorgia - La cura per me", "image": "/giorgia.jpg" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/peyote.jpg" },
        { "name": "Rose Villain - Fuorilegge", "image": "/rose_villain.jpeg" },
        { "name": "Olly - Balorda nostalgia", "image": "/olly.jpg" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/elodie.jpg" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/Shablo.jpg" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/Massimo_ranieri.jpg" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/tony_effe.jpg" },
        { "name": "Serena Brancale - Anema e core", "image": "/Serena_Brancale.jpg" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/brunori-sas.jpg" },
        { "name": "Modà - Non ti dimentico", "image": "/moda.jpg" },
        { "name": "Clara - Febbre", "image": "/clara.jpg" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi.jpg" },
        { "name": "Fedez - Battito", "image": "/fedez.jpg" },
        { "name": "Bresh - La tana del granchio", "image": "/bresh.jpg" },
        { "name": "Sarah Toscano - Amarcord", "image": "/sarah.jpg" },
        { "name": "Joan Thiele - Eco", "image": "/joan-thiele.jpg" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/rocco_hunt.jpg" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/michielin.jpg" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/the_kolors.jpg" }
    ],
    "5": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/gaia.jpg" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/gabbani.jpg" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/rkomi.jpg" },
        { "name": "Noemi - Se t'innamori muori", "image": "/noemi.jpg" },
        { "name": "Irama - Lentamente", "image": "/irama.jpg" },
        { "name": "Coma_Cose - Cuoricini", "image": "/coma-cose.jpg" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/cristicchi.jpg" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/marcella_bella.jpg" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/achille-lauro.jpg" },
        { "name": "Giorgia - La cura per me", "image": "/giorgia.jpg" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/peyote.jpg" },
        { "name": "Rose Villain - Fuorilegge", "image": "/rose_villain.jpeg" },
        { "name": "Olly - Balorda nostalgia", "image": "/olly.jpg" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/elodie.jpg" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/Shablo.jpg" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/Massimo_ranieri.jpg" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/tony_effe.jpg" },
        { "name": "Serena Brancale - Anema e core", "image": "/Serena_Brancale.jpg" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/brunori-sas.jpg" },
        { "name": "Modà - Non ti dimentico", "image": "/moda.jpg" },
        { "name": "Clara - Febbre", "image": "/clara.jpg" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi.jpg" },
        { "name": "Fedez - Battito", "image": "/fedez.jpg" },
        { "name": "Bresh - La tana del granchio", "image": "/bresh.jpg" },
        { "name": "Sarah Toscano - Amarcord", "image": "/sarah.jpg" },
        { "name": "Joan Thiele - Eco", "image": "/joan-thiele.jpg" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/rocco_hunt.jpg" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/michielin.jpg" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/the_kolors.jpg" }
    ],
    
    
}

export const allArtists = Object.values(artistOrder["1"]).flat()