const artistOrder: Record<string, string[]> = {
    "1": [
        "Gaia - Chiamo io chiami tu",
        "Francesco Gabbani - Viva la vita",
        "Rkomi - Il ritmo delle cose",
        "Noemi - Se t'innamori muori",
        "Irama - Lentamente",
        "Coma_Cose - Cuoricini",
        "Simone Cristicchi - Quando sarai piccola",
        "Marcella Bella - Pelle diamante",
        "Achille Lauro - Incoscienti giovani",
        "Giorgia - La cura per me",
        "Willie Peyote - Grazie ma no grazie",
        "Rose Villain - Fuorilegge",
        "Olly - Balorda nostalgia",
        "Elodie - Dimenticarsi alle 7",
        "Shablo feat Guè, Joshua e Tormento - La mia parola",
        "Massimo Ranieri - Tra le mani un cuore",
        "Tony Effe - Damme 'na mano",
        "Serena Brancale - Anema e core",
        "Brunori Sas - L'albero delle noci",
        "Modà - Non ti dimentico",
        "Clara - Febbre",
        "Lucio Corsi - Volevo essere un duro",
        "Fedez - Battito",
        "Bresh - La tana del granchio",
        "Sarah Toscano - Amarcord",
        "Joan Thiele - Eco",
        "Rocco Hunt - Mille vote ancora",
        "Francesca Michielin - Fango in paradiso",
        "The Kolors - Tu con chi fai l'amore",
    ],
    "2": [
        "Francesco Gabbani - Viva la vita",
        "Rkomi - Il ritmo delle cose",
        "Noemi - Se t'innamori muori",
        "Irama - Lentamente",
        "Artist 25",
        "Gaia - Chiamo io chiami tu",
        "Simone Cristicchi - Quando sarai piccola",
        "Marcella Bella - Pelle diamante",
        "Achille Lauro - Incoscienti giovani",
        "Giorgia - La cura per me",
        "Coma_Cose - Cuoricini",
        "Rose Villain - Fuorilegge",
        "Olly - Balorda nostalgia",
        "Elodie - Dimenticarsi alle 7",
        "Shablo feat Guè, Joshua e Tormento - La mia parola",
        "Willie Peyote - Grazie ma no grazie",
        "Tony Effe - Damme 'na mano",
        "Serena Brancale - Anema e core",
        "Brunori Sas - L'albero delle noci",
        "Modà - Non ti dimentico",
        "Massimo Ranieri - Tra le mani un cuore",
        "Clara - Febbre",
        "Lucio Corsi - Volevo essere un duro",
        "Artist 19",
        "Artist 24",
        "Joan Thiele - Eco",
        "Rocco Hunt - Mille vote ancora",
        "Francesca Michielin - Fango in paradiso",
        "The Kolors - Tu con chi fai l'amore",
    ],
    "3": [
        "Rkomi - Il ritmo delle cose",
        "Noemi - Se t'innamori muori",
        "Irama - Lentamente",
        "Artist 25",
        "Gaia - Chiamo io chiami tu",
        "Francesco Gabbani - Viva la vita",
        "Marcella Bella - Pelle diamante",
        "Achille Lauro - Incoscienti giovani",
        "Giorgia - La cura per me",
        "Joan Thiele - Eco",
        "Coma_Cose - Cuoricini",
        "Simone Cristicchi - Quando sarai piccola",
        "Olly - Balorda nostalgia",
        "Elodie - Dimenticarsi alle 7",
        "Shablo feat Guè, Joshua e Tormento - La mia parola",
        "Willie Peyote - Grazie ma no grazie",
        "Rose Villain - Fuorilegge",
        "Serena Brancale - Anema e core",
        "Brunori Sas - L'albero delle noci",
        "Modà - Non ti dimentico",
        "Massimo Ranieri - Tra le mani un cuore",
        "Tony Effe - Damme 'na mano",
        "Clara - Febbre",
        "Lucio Corsi - Volevo essere un duro",
        "Artist 19",
        "Artist 24",
        "Rocco Hunt - Mille vote ancora",
        "Francesca Michielin - Fango in paradiso",
        "The Kolors - Tu con chi fai l'amore",
    ],
    "4": [
        "Noemi - Se t'innamori muori",
        "Irama - Lentamente",
        "Artist 25",
        "Gaia - Chiamo io chiami tu",
        "Francesco Gabbani - Viva la vita",
        "Rkomi - Il ritmo delle cose",
        "Achille Lauro - Incoscienti giovani",
        "Giorgia - La cura per me",
        "Joan Thiele - Eco",
        "Coma_Cose - Cuoricini",
        "Simone Cristicchi - Quando sarai piccola",
        "Marcella Bella - Pelle diamante",
        "Elodie - Dimenticarsi alle 7",
        "Shablo feat Guè, Joshua e Tormento - La mia parola",
        "Rocco Hunt - Mille vote ancora",
        "Willie Peyote - Grazie ma no grazie",
        "Rose Villain - Fuorilegge",
        "Olly - Balorda nostalgia",
        "Brunori Sas - L'albero delle noci",
        "Modà - Non ti dimentico",
        "Massimo Ranieri - Tra le mani un cuore",
        "Tony Effe - Damme 'na mano",
        "Clara - Febbre",
        "Serena Brancale - Anema e core",
        "Lucio Corsi - Volevo essere un duro",
        "Artist 19",
        "Artist 24",
        "Francesca Michielin - Fango in paradiso",
        "The Kolors - Tu con chi fai l'amore",
    ],
    "5": [
        "Irama - Lentamente",
        "Artist 25",
        "Gaia - Chiamo io chiami tu",
        "Francesco Gabbani - Viva la vita",
        "Rkomi - Il ritmo delle cose",
        "Noemi - Se t'innamori muori",
        "Giorgia - La cura per me",
        "Joan Thiele - Eco",
        "Coma_Cose - Cuoricini",
        "Simone Cristicchi - Quando sarai piccola",
        "Marcella Bella - Pelle diamante",
        "Achille Lauro - Incoscienti giovani",
        "Shablo feat Guè, Joshua e Tormento - La mia parola",
        "Rocco Hunt - Mille vote ancora",
        "Willie Peyote - Grazie ma no grazie",
        "Rose Villain - Fuorilegge",
        "Olly - Balorda nostalgia",
        "Elodie - Dimenticarsi alle 7",
        "Modà - Non ti dimentico",
        "Francesca Michielin - Fango in paradiso",
        "Massimo Ranieri - Tra le mani un cuore",
        "Tony Effe - Damme 'na mano",
        "Clara - Febbre",
        "Serena Brancale - Anema e core",
        "Lucio Corsi - Volevo essere un duro",
        "Brunori Sas - L'albero delle noci",
        "Artist 19",
        "Artist 24",
        "The Kolors - Tu con chi fai l'amore",
    ],
}


export default artistOrder