export interface Artist {
    name: string
    image: string
}

export const artistOrder: Record<string, Artist[]> = {
    "1": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Noemi - Se t'innamori muori", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Irama - Lentamente", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Coma_Cose - Cuoricini", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Giorgia - La cura per me", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rose Villain - Fuorilegge", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Olly - Balorda nostalgia", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Serena Brancale - Anema e core", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Modà - Non ti dimentico", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Clara - Febbre", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Fedez - Battito", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Bresh - La tana del granchio", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Sarah Toscano - Amarcord", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Joan Thiele - Eco", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" }
    ],
    "2": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Noemi - Se t'innamori muori", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Irama - Lentamente", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Coma_Cose - Cuoricini", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Giorgia - La cura per me", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rose Villain - Fuorilegge", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Olly - Balorda nostalgia", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Serena Brancale - Anema e core", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Modà - Non ti dimentico", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Clara - Febbre", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Fedez - Battito", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Bresh - La tana del granchio", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Sarah Toscano - Amarcord", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Joan Thiele - Eco", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" }
    ],
    "3": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Noemi - Se t'innamori muori", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Irama - Lentamente", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Coma_Cose - Cuoricini", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Giorgia - La cura per me", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rose Villain - Fuorilegge", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Olly - Balorda nostalgia", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Serena Brancale - Anema e core", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Modà - Non ti dimentico", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Clara - Febbre", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Fedez - Battito", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Bresh - La tana del granchio", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Sarah Toscano - Amarcord", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Joan Thiele - Eco", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" }
    ],
    "4": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Noemi - Se t'innamori muori", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Irama - Lentamente", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Coma_Cose - Cuoricini", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Giorgia - La cura per me", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rose Villain - Fuorilegge", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Olly - Balorda nostalgia", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Serena Brancale - Anema e core", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Modà - Non ti dimentico", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Clara - Febbre", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Fedez - Battito", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Bresh - La tana del granchio", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Sarah Toscano - Amarcord", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Joan Thiele - Eco", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" }
    ],
    "5": [
        { "name": "Gaia - Chiamo io chiami tu", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesco Gabbani - Viva la vita", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rkomi - Il ritmo delle cose", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Noemi - Se t'innamori muori", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Irama - Lentamente", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Coma_Cose - Cuoricini", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Simone Cristicchi - Quando sarai piccola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Marcella Bella - Pelle diamante", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Achille Lauro - Incoscienti giovani", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Giorgia - La cura per me", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Willie Peyote - Grazie ma no grazie", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rose Villain - Fuorilegge", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Olly - Balorda nostalgia", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Elodie - Dimenticarsi alle 7", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Shablo feat Guè, Joshua e Tormento - La mia parola", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Massimo Ranieri - Tra le mani un cuore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Tony Effe - Damme 'na mano", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Serena Brancale - Anema e core", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Brunori Sas - L'albero delle noci", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Modà - Non ti dimentico", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Clara - Febbre", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Lucio Corsi - Volevo essere un duro", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Fedez - Battito", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Bresh - La tana del granchio", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Sarah Toscano - Amarcord", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Joan Thiele - Eco", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Rocco Hunt - Mille vote ancora", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "Francesca Michielin - Fango in paradiso", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" },
        { "name": "The Kolors - Tu con chi fai l'amore", "image": "/lucio-corsi-sanremo.jpg?height=100&width=100" }
    ],
}

export const allArtists = Object.values(artistOrder).flat()